name: Release

on:
  push:
    branches:
      - main
jobs:
  terraform:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0


      - name: install terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: latest
      
      - name: install azure cli
        uses: pip install azure-cli
        with:
          version: latest

      - name: azure login
        uses: az login --tenant ${{ secrets.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}
      
      - name: terraform init,validate,plan
        uses: terraform init && terraform validate && terraform plan


      