name: Release

on:
  push:
    branches:
      - main
jobs:
  terraform:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0


      - name: install terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
      
      - name: install azure cli
        run: |
          pip install azure-cli
          az upgrade  --yes

      - name: azure login
        run: az login --tenant ${{ secrets.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}
      
      - name: terraform init,validate,plan
        run: terraform init && terraform validate && terraform plan
